FROM node:22-alpine3.19

WORKDIR /app

COPY . .

RUN npm install

# RUN npx sequelize-cli db:create --url 'postgres://db_admin:1234@localhost:5433/my_db'

# RUN npx sequelize-cli db:migrate --url 'postgres://db_admin:1234@localhost:5433/my_db'

CMD ["node", "app.js"]